/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ConfigurationsRouteImport } from './routes/configurations'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as DoctorSlotRouteImport } from './routes/doctorSlot'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MasterRouteImport } from './routes/master'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TeleconsultationRouteImport } from './routes/teleconsultation'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as UserManagementUsersRouteImport } from './routes/user-management-users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsRoute = ConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorSlotRoute = DoctorSlotRouteImport.update({
  id: '/doctorSlot',
  path: '/doctorSlot',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeleconsultationRoute = TeleconsultationRouteImport.update({
  id: '/teleconsultation',
  path: '/teleconsultation',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementUsersRoute = UserManagementUsersRouteImport.update({
  id: '/user-management-users',
  path: '/user-management-users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/change-password': typeof ChangePasswordRoute
  '/configurations': typeof ConfigurationsRoute
  '/consultation': typeof ConsultationRoute
  '/doctorSlot': typeof DoctorSlotRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/queue': typeof QueueRoute
  '/registration': typeof RegistrationRoute
  '/reports': typeof ReportsRoute
  '/teleconsultation': typeof TeleconsultationRoute
  '/user-management': typeof UserManagementRoute
  '/user-management-users': typeof UserManagementUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/change-password': typeof ChangePasswordRoute
  '/configurations': typeof ConfigurationsRoute
  '/consultation': typeof ConsultationRoute
  '/doctorSlot': typeof DoctorSlotRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/queue': typeof QueueRoute
  '/registration': typeof RegistrationRoute
  '/reports': typeof ReportsRoute
  '/teleconsultation': typeof TeleconsultationRoute
  '/user-management': typeof UserManagementRoute
  '/user-management-users': typeof UserManagementUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/change-password': typeof ChangePasswordRoute
  '/configurations': typeof ConfigurationsRoute
  '/consultation': typeof ConsultationRoute
  '/doctorSlot': typeof DoctorSlotRoute
  '/lab': typeof LabRoute
  '/login': typeof LoginRoute
  '/master': typeof MasterRoute
  '/patients': typeof PatientsRoute
  '/pharmacy': typeof PharmacyRoute
  '/queue': typeof QueueRoute
  '/registration': typeof RegistrationRoute
  '/reports': typeof ReportsRoute
  '/teleconsultation': typeof TeleconsultationRoute
  '/user-management': typeof UserManagementRoute
  '/user-management-users': typeof UserManagementUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/billing'
    | '/change-password'
    | '/configurations'
    | '/consultation'
    | '/doctorSlot'
    | '/lab'
    | '/login'
    | '/master'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/registration'
    | '/reports'
    | '/teleconsultation'
    | '/user-management'
    | '/user-management-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/billing'
    | '/change-password'
    | '/configurations'
    | '/consultation'
    | '/doctorSlot'
    | '/lab'
    | '/login'
    | '/master'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/registration'
    | '/reports'
    | '/teleconsultation'
    | '/user-management'
    | '/user-management-users'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/billing'
    | '/change-password'
    | '/configurations'
    | '/consultation'
    | '/doctorSlot'
    | '/lab'
    | '/login'
    | '/master'
    | '/patients'
    | '/pharmacy'
    | '/queue'
    | '/registration'
    | '/reports'
    | '/teleconsultation'
    | '/user-management'
    | '/user-management-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ConfigurationsRoute: typeof ConfigurationsRoute
  ConsultationRoute: typeof ConsultationRoute
  DoctorSlotRoute: typeof DoctorSlotRoute
  LabRoute: typeof LabRoute
  LoginRoute: typeof LoginRoute
  MasterRoute: typeof MasterRoute
  PatientsRoute: typeof PatientsRoute
  PharmacyRoute: typeof PharmacyRoute
  QueueRoute: typeof QueueRoute
  RegistrationRoute: typeof RegistrationRoute
  ReportsRoute: typeof ReportsRoute
  TeleconsultationRoute: typeof TeleconsultationRoute
  UserManagementRoute: typeof UserManagementRoute
  UserManagementUsersRoute: typeof UserManagementUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations': {
      id: '/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof ConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctorSlot': {
      id: '/doctorSlot'
      path: '/doctorSlot'
      fullPath: '/doctorSlot'
      preLoaderRoute: typeof DoctorSlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teleconsultation': {
      id: '/teleconsultation'
      path: '/teleconsultation'
      fullPath: '/teleconsultation'
      preLoaderRoute: typeof TeleconsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management-users': {
      id: '/user-management-users'
      path: '/user-management-users'
      fullPath: '/user-management-users'
      preLoaderRoute: typeof UserManagementUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ConfigurationsRoute: ConfigurationsRoute,
  ConsultationRoute: ConsultationRoute,
  DoctorSlotRoute: DoctorSlotRoute,
  LabRoute: LabRoute,
  LoginRoute: LoginRoute,
  MasterRoute: MasterRoute,
  PatientsRoute: PatientsRoute,
  PharmacyRoute: PharmacyRoute,
  QueueRoute: QueueRoute,
  RegistrationRoute: RegistrationRoute,
  ReportsRoute: ReportsRoute,
  TeleconsultationRoute: TeleconsultationRoute,
  UserManagementRoute: UserManagementRoute,
  UserManagementUsersRoute: UserManagementUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
